DROP TABLE IF EXISTS score;

CREATE TABLE score (
	id SERIAL PRIMARY KEY,
	name TEXT,
	time TIMESTAMP,
	is_deleted INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
